graceshopper-samurais/graceshopper-project

- .travis.yml
- package-lock.json
- package.json
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
Referenced in my Slack message: We neglected to finish a couple of items referenced in the README before everyone pulled down the master today. I did these (it was really about putting the project name in package.json and .travis.yml files which it uses to calculate the database names). I did this on my local machine, ran npm install and npm run start-dev and confirmed that the server started without crashing and I could hit the site with my web browser
> chore: update package.json and .travis.yml files

- client/components/allProducts.js
- client/components/index.js
- client/routes.js
- client/store/index.js
- client/store/products.js
- client/store/products.spec.js
- server/api/index.js
- server/api/products.js
- server/api/products.spec.js
Finished an All Products slice.
> All products

- client/components/singleProduct.js
- client/store/singleProduct.js
Still working on singleProduct reducer and integration of component with AllProducts component
> Single product

- server/db/models/product.js
- server/db/models/product.spec.js
- server/db/models/user.js
Updated user model, created product model, started product tests.
Closes #16, closes #17
> User and product models

- server/db/models/product.spec.js
- server/db/models/user.spec.js
updated user and product model specs
> user and product model specs

- script/seed2.js
- server/db/models/cart.js
- server/db/models/index.js
> feat(db): create cart model and associations

- client/components/FullCart.js
- client/routes.js
- client/store/index.js
- client/store/singleCart.js
- script/seed2.js
- server/api/cart.js
- server/api/index.js
cart backend GET route + start to cart frontend
> Cart backend

- script/seed.js
Added cart items with quantities for the first 5 users, varying the number of items and quantities of each
closes #2
> chore: added seeding for carts

- server/api/users.js
I figured out how to protect api routes.  So far, I've only implemented this for GET api/users, but we could obviously implement it in other cases.  I want to run this by Ben tomorrow before we do this _everywhere._
> feat(api): add security to GET api/users

- client/components/navbar.js
> fix(react): fix navbar formatting error

- client/components/allProducts.js
- client/store/products.js
> frontEndwithBen

- client/store/products.js
- server/api/cart.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/product.js
- server/db/models/productorder.js
Models and associations updated
> #60 models redefinition

- client/store/products.js
- server/api/cart.js
> no changes for now

- client/components/allProducts.js
- client/store/products.js
- client/store/singleCart.js
- server/api/cart.js
Have not tested with back end yet!
> feat(react/redux): add to cart functionality for all products view

- server/api/index.js
- server/api/users.js
get route for cart backend (not tested yet!)
> cart backend routes update

- script/seed.js
Seeded productOrder and new order tables.
> chore: add orderProduct data to seed file

- client/components/DeleteButton.js
- client/components/FullCart.js
- client/store/singleCart.js
- server/api/users.js
Delete component created and added to FullCart component along with associated addition to singleCart reducer and users.js api route.
> feat: delete button

- client/store/singleCart.js
- server/api/users.js
- server/db/models/productorder.js
- server/index.js
very messy post route. will clean this up this afternoon
> Add to cart post route

- client/components/FullCart.js
- client/store/singleCart.js
- server/api/users.js
> fix: start to fix store for ADD TO CART and fixed backend route

- client/components/FullCart.js
- client/store/singleCart.js
- server/api/users.js
> still editing update cart quantity

- client/store/singleCart.js
- server/api/users.js
The "addToCart" from the AllProducts view is fully functional, front-end to back-end.  I also cleaned up my api route, and added some documentation to make it easier to understand what was happening.
Closes #62
> fix(slice): fix full slice for addToCart POST route - fully functioning

- client/components/FullCart.js
- client/components/UpdateQuantity.js
- client/store/singleCart.js
- server/api/users.js
PUT route fully functional!
Close #6
> Fix put route

- client/components/allProducts.js
- package-lock.json
- package.json
Spinner added using the "Watch" animation
https://www.npmjs.com/package/react-loader-spinner
> React loader spinner

- client/components/CartIcon.js
cart icon tracks with guest cart, except initial load -
still need to address initial state loading issue
where is the best place to initially put the carts on state?
> updated cart icon for guest cart

- client/components/allProducts.js
- client/store/products.js
Fully functional front-end to back-end!
> Admin delete product

- client/components/FullCart.js
- client/components/GuestCart.js
- public/_cart.scss
- public/main.scss
> Guest cart styling

- client/components/singleProduct.spec.js
wrote one test, though didn't get to run it.
> testing not my forte

- client/components/AddToCartButton.js
- client/components/CartIcon.js
- client/components/allProducts.js
- client/store/cartIcon.js
- client/store/guestCart.js
- client/store/index.js
- client/store/singleCart.js
Fixed all issues with cartIcon
> Carticon fixes

- client/components/AddToCartButton.js
- client/components/CartIcon.js
- client/components/allProducts.js
- client/store/cartIcon.js
- client/store/guestCart.js
- client/store/index.js
- client/store/singleCart.js
- server/index.js
Fixed error handler function in API routes
> Error handler

- client/components/allProducts.js
- client/components/navbar.js
> feat: create link to Users for admin
